apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-voting-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-voting-db
  template:
    metadata:
      labels:
        app: azure-voting-db
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-voting-db
        image: postgres:15.0-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        ports:
        - containerPort: 5432
          name: psql
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: azure-voting-db
#spec:
#  ports:
#  - port: 5432
#  selector:
#    app: azure-voting-db
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-voting-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-voting-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-voting-app
        image: myimage:latest
        ports:
        - containerPort: 8080
          name: http-web-svc
        # resources:
        #   requests:
        #     cpu: 250m
        #     memory: 128Mi
        #   limits:
        #     cpu: 500m
        #     memory: 128Mi
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:mypassword@azure-voting-db"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-web-svc
  selector:
    app: azure-voting-app
