apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-voting-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-voting-db
  template:
    metadata:
      labels:
        app: azure-voting-db
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-voting-db
        image: postgres:15.0-alpine
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        ports:
        - containerPort: 5432
          name: psql
        resources:
          limits:
            memory: "120Mi"
            cpu: "3m"
          requests:
            memory: "40Mi"
            cpu: "1m"
        volumeMounts:
        - name: mypvc
          mountPath: "/var/lib/postgresql/data"
          subPath: "data"
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: pvc-azuredisk
---
apiVersion: v1
kind: Service
metadata:
  name: azure-voting-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: azure-voting-db