apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-voting-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-voting-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-voting-app
        image: ghcr.io/pauldotyu/azure-voting-app-rust:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-web-svc
        envFrom:
        - configMapRef:
            name: azure-voting-config
