apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-voting-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-voting-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-voting-app
        image: ghcr.io/pauldotyu/azure-voting-app-rust:v0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: web
          failureThreshold: 10
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:mypassword@azure-voting-db"
        - name: FIRST_VALUE
          value: "Dogs"
        - name: SECOND_VALUE
          value: "Cats"
        resources:
          limits:
            memory: "30Mi"
            cpu: "6m"
          requests:      
            memory: "10Mi"
            cpu: "2m"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-voting-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: azure-voting-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: azure-voting-app
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - backend:
          service:
            name: azure-voting-app
            port:
              number: 80
        path: /
        pathType: Prefix
