---
apiVersion: v1
kind: Service
metadata:
  name: azure-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-web-svc
  selector:
    app: azure-voting-app

---
apiVersion: v1
kind: Service
metadata:
  name: azure-voting-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: azure-voting-db